INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRONYME) VALUES 
(10, 'Italie', 'ITA'),
(12, 'Australie', 'AUS'),
(5, 'Pays-Bas', 'NED'),
(4, 'Espagne', 'ESP'),
(8, 'Grande-Bretagne', 'GBR'),
(2, 'France', 'FRA'),
(3, 'Luxembourg', 'LUX'),
(6, 'Russie', 'RUS'),
(7, 'Belgique', 'BEL'),
(1, 'Danemark', 'DEN'),
(9, 'États-Unis', 'USA'),
(11, 'Kazakhstan', 'KAZ'),
(13, 'Norvège', 'NOR'),
(14, 'Biélorussie', 'BLR'),
(15, 'Slovaquie', 'SVK'),
(16, 'Pologne', 'POL'),
(17, 'Slovénie', 'SLO'),
(18, 'Allemagne', 'GER'),
(19, 'Nouvelle Zélande', 'NZL'),
(20, 'Suisse', 'SUI'),
(21, 'Luxembourg', 'LUX'),
(22, 'Japon', 'JPN'),
(23, 'Canada', 'CAN'),
(24, 'Suède', 'SWE'),
(25, 'Brésil', 'BRA'),
(26, 'République Tchèque', 'CZE'),
(27, 'Portugal', 'POR'),
(28, 'Irlande', 'IRL'),
(29, 'Lettonie', 'LAT'),
(30, 'Costa Rica', 'CRC'),
(31, 'Colombie', 'COL'),
(32, 'Lituanie', 'LTU'),
(33, 'Afrique du Sud', 'RSA'),
(34, 'Ouzbékistan', 'UZB');



