INSERT INTO DIRECTEUR_SPORTIF (DIRS_NUM, DIRS_NOM, DIRS_PRENOM) VALUES 
(1, 'MAUDUIT', 'Philippe'),
(2, 'GUIDI', 'Fabrizio'),
(3, 'LAVENU', 'Vincent'),
(4, 'JURDIE', 'Julien'),
(5, 'ANDERSEN', 'Kim'),
(6, 'GALLOPIN', 'Alain'),
(7, 'ARRIETA', 'JosÃ© Luis'),
(8, 'JAIMERENA', 'JosÃ©-Luis'),
(9, 'VERHOEVEN', 'Nico'),
(10, 'MAASSEN', 'Frans'),
(11, 'PIVA', 'Valerio'),
(12, 'SCHMIDT', 'Torsten'),
(13, 'GONZALEZ GALDEANO', 'Alvaro'),
(14, 'GUERRERO', 'Oscar'),
(15, 'PEETERS', 'Wilfried'),
(16, 'BRAMATI', 'Davide'),
(17, 'PORTAL', 'Nicolas'),
(18, 'KNAVEN', 'Servais'),
(19, 'ROUS', 'Didier'),
(20, 'DELOEUIL', 'Alain'),
(21, 'WEGELIUS', 'Charles'),
(22, 'FERNANDEZ', 'Bingen'),
(23, 'LELANGUE', 'John'),
(24, 'BALDATO', 'Fabio'),
(25, 'FLICKINGER', 'Andy'),
(26, 'MOTTIER', 'IsmaÃ«l'),
(27, 'BRICAUD', 'Thierry'),
(28, 'PINEAU', 'Franck'),
(29, 'GUILLE', 'Nicolas'),
(30, 'LEBRETON', 'Lylian'),
(31, 'MAINI', 'Orlando'),
(32, 'VICINO', 'Bruno'),
(33, 'VAN DER SCHUEREN', 'Hilaire'),
(34, 'VAN POPPEL', 'Jean-Paul'),
(35, 'SEDOUN', 'Dmitri'),
(36, 'FOFONOV', 'Dmitriy'),
(37, 'WHITE', 'Matthew'),
(38, 'STEPHENS', 'Neil'),
(39, 'FRISON', 'Herman'),
(40, 'WAUTERS', 'Marc'),
(41, 'GUIBERTEAU', 'Christian'),
(42, 'KEMNA', 'Rudi'),
(43, 'ZANATTA', 'Stefano'),
(44, 'SCIREA', 'Mario'),
