INSERT INTO PAYS(PAYS_NUM, PAYS_NOM) VALUES 
(10, ' Italie'),
(12, ' Australie'),
(5, ' Pays-Bas'),
(4, ' Espagne'),
(8, ' Grande-Bretagne'),
(2, ' France'),
(3, ' Luxembourg'),
(6, ' Russie'),
(7, ' Belgique'),
(1, ' Danemark'),
(9, 'tats-Unis'),
(11, ' Kazakhstan'),
