--------------------------------------------------------
--  Fichier créé - lundi-juin-09-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PORTER
--------------------------------------------------------

  CREATE TABLE "G11_FLIGHT"."PORTER" 
   (	"TOUR_ANNEE" NUMBER(4,0), 
	"ETAPE_NUM" NUMBER(2,0), 
	"MAILLOT_COULEUR" VARCHAR2(20 BYTE), 
	"PART_NUM" NUMBER(3,0), 
	 CONSTRAINT "PK_PORTER" PRIMARY KEY ("TOUR_ANNEE", "ETAPE_NUM", "MAILLOT_COULEUR") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD50_DATA" 
 PCTTHRESHOLD 50;
REM INSERTING into G11_FLIGHT.PORTER
SET DEFINE OFF;
Insert into G11_FLIGHT.PORTER (TOUR_ANNEE,ETAPE_NUM,MAILLOT_COULEUR,PART_NUM) values ('2013','21','jaune','1');
Insert into G11_FLIGHT.PORTER (TOUR_ANNEE,ETAPE_NUM,MAILLOT_COULEUR,PART_NUM) values ('2014','3','pois','4');
Insert into G11_FLIGHT.PORTER (TOUR_ANNEE,ETAPE_NUM,MAILLOT_COULEUR,PART_NUM) values ('2013','21','vert','12');
Insert into G11_FLIGHT.PORTER (TOUR_ANNEE,ETAPE_NUM,MAILLOT_COULEUR,PART_NUM) values ('2014','3','jaune','12');
Insert into G11_FLIGHT.PORTER (TOUR_ANNEE,ETAPE_NUM,MAILLOT_COULEUR,PART_NUM) values ('2014','3','blanc','22');
Insert into G11_FLIGHT.PORTER (TOUR_ANNEE,ETAPE_NUM,MAILLOT_COULEUR,PART_NUM) values ('2014','3','vert','25');
Insert into G11_FLIGHT.PORTER (TOUR_ANNEE,ETAPE_NUM,MAILLOT_COULEUR,PART_NUM) values ('2013','21','pois','34');
Insert into G11_FLIGHT.PORTER (TOUR_ANNEE,ETAPE_NUM,MAILLOT_COULEUR,PART_NUM) values ('2013','21','blanc','45');
--------------------------------------------------------
--  DDL for Index PK_PORTER
--------------------------------------------------------

  CREATE UNIQUE INDEX "G11_FLIGHT"."PK_PORTER" ON "G11_FLIGHT"."PORTER" ("TOUR_ANNEE", "ETAPE_NUM", "MAILLOT_COULEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_FK_PORTER_PARTICIPANT
--------------------------------------------------------

  CREATE INDEX "G11_FLIGHT"."I_FK_PORTER_PARTICIPANT" ON "G11_FLIGHT"."PORTER" ("PART_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD50_IND" ;
--------------------------------------------------------
--  DDL for Index I_FK_PORTER_ETAPE
--------------------------------------------------------

  CREATE INDEX "G11_FLIGHT"."I_FK_PORTER_ETAPE" ON "G11_FLIGHT"."PORTER" ("TOUR_ANNEE", "ETAPE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD50_IND" ;
--------------------------------------------------------
--  Constraints for Table PORTER
--------------------------------------------------------

  ALTER TABLE "G11_FLIGHT"."PORTER" ADD CONSTRAINT "CHK_MAILLOT" CHECK (MAILLOT_COULEUR='jaune' OR MAILLOT_COULEUR='vert' OR MAILLOT_COULEUR='pois' OR MAILLOT_COULEUR='blanc') ENABLE;
 
  ALTER TABLE "G11_FLIGHT"."PORTER" ADD CONSTRAINT "PK_PORTER" PRIMARY KEY ("TOUR_ANNEE", "ETAPE_NUM", "MAILLOT_COULEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD50_DATA"  ENABLE;
 
  ALTER TABLE "G11_FLIGHT"."PORTER" MODIFY ("TOUR_ANNEE" NOT NULL ENABLE);
 
  ALTER TABLE "G11_FLIGHT"."PORTER" MODIFY ("ETAPE_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "G11_FLIGHT"."PORTER" MODIFY ("MAILLOT_COULEUR" NOT NULL ENABLE);
 
  ALTER TABLE "G11_FLIGHT"."PORTER" MODIFY ("PART_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PORTER
--------------------------------------------------------

  ALTER TABLE "G11_FLIGHT"."PORTER" ADD CONSTRAINT "FK_PORTER_ETAPE" FOREIGN KEY ("TOUR_ANNEE", "ETAPE_NUM")
	  REFERENCES "G11_FLIGHT"."ETAPE" ("TOUR_ANNEE", "ETAPE_NUM") ENABLE;
 
  ALTER TABLE "G11_FLIGHT"."PORTER" ADD CONSTRAINT "FK_PORTER_PARTICIPANT" FOREIGN KEY ("TOUR_ANNEE", "PART_NUM")
	  REFERENCES "G11_FLIGHT"."PARTICIPANT" ("TOUR_ANNEE", "PART_NUM") ENABLE;
