INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (1, 1, 1);

INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (2, 1, 2);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (2, 2, 1);

INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (3, 1, 5);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (3, 2, 3);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (3, 3, 2);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (3, 4, 1);

INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (4, 1, 10);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (4, 2, 8);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (4, 3, 6);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (4, 4, 4);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (4, 5, 2);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (4, 6, 1);

INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (5, 1, 25);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (5, 2, 20);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (5, 3, 16);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (5, 4, 14);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (5, 5, 12);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (5, 6, 10);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (5, 7, 8);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (5, 8, 6);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (5, 9, 4);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (5, 10, 2);

INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (6, 1, 30);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (6, 2, 25);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (6, 3, 22);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (6, 4, 19);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (6, 5, 17);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (6, 6, 15);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (6, 7, 13);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (6, 8, 11);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (6, 9, 9);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (6, 10, 7);

INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (7, 1, 45);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (7, 2, 40);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (7, 3, 37);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (7, 4, 35);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (7, 5, 33);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (7, 6, 31);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (7, 7, 29);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (7, 8, 27);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (7, 9, 25);
INSERT INTO BAREME (CAT_NUM, BAREME_PLACE, BAREME_PTS) VALUES (7, 10, 23);