INSERT INTO CATEGORIE (CAT_NUM, CAT_LIB, MAILLOT_COULEUR) VALUES (1, 'Col de catégorie 4', 'pois');
INSERT INTO CATEGORIE (CAT_NUM, CAT_LIB, MAILLOT_COULEUR) VALUES (2, 'Col de catégorie 3', 'pois');
INSERT INTO CATEGORIE (CAT_NUM, CAT_LIB, MAILLOT_COULEUR) VALUES (3, 'Col de catégorie 2', 'pois');
INSERT INTO CATEGORIE (CAT_NUM, CAT_LIB, MAILLOT_COULEUR) VALUES (4, 'Col de catégorie 1', 'pois');
INSERT INTO CATEGORIE (CAT_NUM, CAT_LIB, MAILLOT_COULEUR) VALUES (5, 'Col hors catégorie', 'pois');
INSERT INTO CATEGORIE (CAT_NUM, CAT_LIB, MAILLOT_COULEUR) VALUES (6, 'Sprint intermédiaire', 'vert');
INSERT INTO CATEGORIE (CAT_NUM, CAT_LIB, MAILLOT_COULEUR) VALUES (7, 'Sprint final', 'vert');

4


