INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(10, 'Italie', 'ITA');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(12, 'Australie', 'AUS');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(5, 'Pays-Bas', 'NED');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(4, 'Espagne', 'ESP');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(8, 'Grande-Bretagne', 'GBR');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(2, 'France', 'FRA');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(3, 'Luxembourg', 'LUX');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(6, 'Russie', 'RUS');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(7, 'Belgique', 'BEL');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(1, 'Danemark', 'DEN');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(9, 'États-Unis', 'USA');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(11, 'Kazakhstan', 'KAZ');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(13, 'Norvège', 'NOR');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(14, 'Biélorussie', 'BLR');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(15, 'Slovaquie', 'SVK');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(16, 'Pologne', 'POL');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(17, 'Slovénie', 'SLO');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(18, 'Allemagne', 'GER');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(19, 'Nouvelle Zélande', 'NZL');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(20, 'Suisse', 'SUI');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(21, 'Luxembourg', 'LUX');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(22, 'Japon', 'JPN');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(23, 'Canada', 'CAN');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(24, 'Suède', 'SWE');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(25, 'Brésil', 'BRA');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(26, 'République Tchèque', 'CZE');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(27, 'Portugal', 'POR');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(28, 'Irlande', 'IRL');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(29, 'Lettonie', 'LAT');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(30, 'Costa Rica', 'CRC');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(31, 'Colombie', 'COL');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(32, 'Lituanie', 'LTU');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(33, 'Afrique du Sud', 'RSA');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(34, 'Ouzbékistan', 'UZB');
INSERT INTO PAYS(PAYS_NUM, PAYS_NOM, PAYS_ACRO)  VALUES(35, 'Estonie', 'EST');



