CREATE SMALLFILE TABLESPACE BD50_DATA
DATAFILE 'e:\oracle\oradata\prod\bd50_d1.dbf' 
SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED 
EXTENT MANAGEMENT LOCAL 
SEGMENT SPACE MANAGEMENT  AUTO;

CREATE SMALLFILE TABLESPACE BD50_IND
DATAFILE 'e:\oracle\oradata\prod\bd50_id1.dbf' 
SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED 
EXTENT MANAGEMENT LOCAL 
SEGMENT SPACE MANAGEMENT  AUTO;

Create user G11_FLIGHT
Identified by G11_FLIGHT
default tablespace BD50_DATA
temporary tablespace TEMP ;