-- -----------------------------------------------------------------------------
--       TABLE : POINT_PASSAGE
-- -----------------------------------------------------------------------------

CREATE TABLE POINT_PASSAGE
   (
    TOUR_ANNEE NUMBER(4)  NOT NULL,
    ETAPE_NUM NUMBER(2)  NOT NULL,
    PT_PASS_NUM NUMBER(38)  NOT NULL,
    PT_PASS_NOM VARCHAR2(75)  NOT NULL,
    PT_PASS_VILLE_NOM VARCHAR2(50) NULL,
    PT_PASS_KM_DEP NUMBER(4,1) NULL,
    PT_PASS_KM_ARR NUMBER(4,1) NULL,
    PT_PASS_ALT NUMBER(4) NULL,
    PT_PASS_HORAIRE VARCHAR2(5) NULL,
    VILLE_NUM NUMBER(5),
    CAT_NUM NUMBER(2)  NULL,
    UTIL_NUM NUMBER(4)  NULL
   ) 
   TABLESPACE BD50_DATA
   PARTITION BY RANGE (TOUR_ANNEE)
	(
		PARTITION POINT_PASSAGE_2012 VALUES LESS THAN (2012),
		PARTITION POINT_PASSAGE_2013 VALUES LESS THAN (2013),
		PARTITION POINT_PASSAGE_2014 VALUES LESS THAN (2014),
		PARTITION POINT_PASSAGE_2015 VALUES LESS THAN (2015),
		PARTITION POINT_PASSAGE_2016 VALUES LESS THAN (2016),
		PARTITION POINT_PASSAGE_2017 VALUES LESS THAN (2017),
		PARTITION POINT_PASSAGE_2018 VALUES LESS THAN (2018),
		PARTITION POINT_PASSAGE_2019 VALUES LESS THAN (2019),
		PARTITION POINT_PASSAGE_2020 VALUES LESS THAN (2020)
	)
   ;
 
-- -----------------------------------------------------------------------------
--       TABLE : TERMINER_ETAPE
-- -----------------------------------------------------------------------------

CREATE TABLE TERMINER_ETAPE
   (
    TOUR_ANNEE NUMBER(4)  NOT NULL,
    PART_NUM NUMBER(3)  NOT NULL,
    ETAPE_NUM NUMBER(2)  NOT NULL,
    CYCLISTE_NOM VARCHAR2(40)  NOT NULL,
    CYCLISTE_PRENOM VARCHAR2(30)  NOT NULL,
    CYCLISTE_PAYS VARCHAR2(50)  NOT NULL,
    CYCLISTE_DATEN DATE  NOT NULL,
    EQUIPE_NOM VARCHAR2(50)  NOT NULL,
    ETAPE_TPS NUMBER(10),
    ETAPE_CLASS NUMBER(3)  NOT NULL,
    ETAPE_PTS_MONT NUMBER(3)  NOT NULL,
    ETAPE_PTS_SPRINT NUMBER(3)  NOT NULL,
	  ETAPE_TPS_ECART NUMBER(10),
    GENE_TPS NUMBER(10),
    GENE_CLASS NUMBER(3),
    GENE_PTS_MONT NUMBER(3)  NOT NULL,
    GENE_CLASS_MONT NUMBER(3),
    GENE_PTS_SPRINT NUMBER(3)  NOT NULL,
    GENE_CLASS_SPRINT NUMBER(3),
    GENE_TPS_ECART NUMBER(10),
	  PT_PASS_NUM NUMBER(3),
	  PT_PASS_NUM_LAST NUMBER(3)
,   CONSTRAINT PK_TERMINER_ETAPE PRIMARY KEY (TOUR_ANNEE, PART_NUM, ETAPE_NUM)  
   )
	ORGANIZATION INDEX
	TABLESPACE BD50_DATA
	PARTITION BY RANGE (TOUR_ANNEE)
		(
			PARTITION TERMINER_ETAPE_2012 VALUES LESS THAN (2012),
			PARTITION TERMINER_ETAPE_2013 VALUES LESS THAN (2013),
			PARTITION TERMINER_ETAPE_2014 VALUES LESS THAN (2014),
			PARTITION TERMINER_ETAPE_2015 VALUES LESS THAN (2015),
			PARTITION TERMINER_ETAPE_2016 VALUES LESS THAN (2016),
			PARTITION TERMINER_ETAPE_2017 VALUES LESS THAN (2017),
			PARTITION TERMINER_ETAPE_2018 VALUES LESS THAN (2018),
			PARTITION TERMINER_ETAPE_2019 VALUES LESS THAN (2019),
			PARTITION TERMINER_ETAPE_2020 VALUES LESS THAN (2020)
		)
   ;
   
-- -----------------------------------------------------------------------------
--       TABLE : PASSER
-- -----------------------------------------------------------------------------

CREATE TABLE PASSER
   (
    TOUR_ANNEE NUMBER(4)  NOT NULL,
    ETAPE_NUM NUMBER(2)  NOT NULL,
    PT_PASS_NUM NUMBER(3)  NOT NULL,
    PART_NUM NUMBER(3)  NOT NULL,
    PASS_CLASS NUMBER(3),
    PASS_TPS NUMBER(10)
,   CONSTRAINT PK_PASSER PRIMARY KEY (TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM) 
   )
   ORGANIZATION INDEX
   TABLESPACE BD50_DATA
	PARTITION BY RANGE (TOUR_ANNEE)
		(
			PARTITION PASSER_2012 VALUES LESS THAN (2012),
			PARTITION PASSER_2013 VALUES LESS THAN (2013),
			PARTITION PASSER_2014 VALUES LESS THAN (2014),
			PARTITION PASSER_2015 VALUES LESS THAN (2015),
			PARTITION PASSER_2016 VALUES LESS THAN (2016),
			PARTITION PASSER_2017 VALUES LESS THAN (2017),
			PARTITION PASSER_2018 VALUES LESS THAN (2018),
			PARTITION PASSER_2019 VALUES LESS THAN (2019),
			PARTITION PASSER_2020 VALUES LESS THAN (2020)
		)
   ;

