-- -----------------------------------------------------------------------------
--       CREATION DES REFERENCES DE TABLE
-- -----------------------------------------------------------------------------


ALTER TABLE CYCLISTE ADD (
     CONSTRAINT FK_CYCLISTE_PAYS
          FOREIGN KEY (PAYS_NUM)
               REFERENCES PAYS (PAYS_NUM))   ;

ALTER TABLE PARTICIPANT ADD (
     CONSTRAINT FK_PARTICIPANT_TOUR
          FOREIGN KEY (TOUR_ANNEE)
               REFERENCES TOUR (TOUR_ANNEE))   ;

ALTER TABLE PARTICIPANT ADD (
     CONSTRAINT FK_PARTICIPANT_EQUIPE
          FOREIGN KEY (TOUR_ANNEE, EQUIPE_NUM)
               REFERENCES EQUIPE (TOUR_ANNEE, EQUIPE_NUM))   ;

ALTER TABLE PARTICIPANT ADD (
     CONSTRAINT FK_PARTICIPANT_POINT_PASSAGE
          FOREIGN KEY (TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM)
               REFERENCES POINT_PASSAGE (TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM))   ;

ALTER TABLE PARTICIPANT ADD (
     CONSTRAINT FK_PARTICIPANT_CYCLISTE
          FOREIGN KEY (CYCLISTE_NUM)
               REFERENCES CYCLISTE (CYCLISTE_NUM))   ;

ALTER TABLE BAREME ADD (
     CONSTRAINT FK_BAREME_CATEGORIE
          FOREIGN KEY (CAT_NUM)
               REFERENCES CATEGORIE (CAT_NUM))   ;

ALTER TABLE EQUIPE ADD (
     CONSTRAINT FK_EQUIPE_TOUR
          FOREIGN KEY (TOUR_ANNEE)
               REFERENCES TOUR (TOUR_ANNEE))   ;

ALTER TABLE EQUIPE ADD (
     CONSTRAINT FK_EQUIPE_PAYS
          FOREIGN KEY (PAYS_NUM)
               REFERENCES PAYS (PAYS_NUM))   ;

ALTER TABLE VILLE ADD (
     CONSTRAINT FK_VILLE_PAYS
          FOREIGN KEY (PAYS_NUM)
               REFERENCES PAYS (PAYS_NUM))   ;

ALTER TABLE POINT_PASSAGE ADD (
     CONSTRAINT FK_POINT_PASSAGE_VILLE
          FOREIGN KEY (VILLE_NUM)
               REFERENCES VILLE (VILLE_NUM))   ;

ALTER TABLE POINT_PASSAGE ADD (
     CONSTRAINT FK_POINT_PASSAGE_CATEGORIE
          FOREIGN KEY (CAT_NUM)
               REFERENCES CATEGORIE (CAT_NUM))   ;

ALTER TABLE POINT_PASSAGE ADD (
     CONSTRAINT FK_POINT_PASSAGE_ETAPE
          FOREIGN KEY (TOUR_ANNEE, ETAPE_NUM)
               REFERENCES ETAPE (TOUR_ANNEE, ETAPE_NUM))   ;

ALTER TABLE POINT_PASSAGE ADD (
     CONSTRAINT FK_POINT_PASSAGE_UTILISATEUR
          FOREIGN KEY (UTIL_NUM)
               REFERENCES UTILISATEUR (UTIL_NUM))   ;

ALTER TABLE CONTROLE ADD (
     CONSTRAINT FK_CONTROLE_PARTICIPANT
          FOREIGN KEY (TOUR_ANNEE, PART_NUM)
               REFERENCES PARTICIPANT (TOUR_ANNEE, PART_NUM))   ;

ALTER TABLE ETAPE ADD (
     CONSTRAINT FK_ETAPE_TOUR
          FOREIGN KEY (TOUR_ANNEE)
               REFERENCES TOUR (TOUR_ANNEE))   ;

ALTER TABLE ETAPE ADD (
     CONSTRAINT FK_ETAPE_VILLE
          FOREIGN KEY (VILLE_NUM_FINIR)
               REFERENCES VILLE (VILLE_NUM))   ;

ALTER TABLE ETAPE ADD (
     CONSTRAINT FK_ETAPE_VILLE2
          FOREIGN KEY (VILLE_NUM_DEBUTER)
               REFERENCES VILLE (VILLE_NUM))   ;

ALTER TABLE TOUR ADD (
     CONSTRAINT FK_TOUR_PARTICIPANT
          FOREIGN KEY (TOUR_ANNEE, SUPER_COMBATIF_NUM)
               REFERENCES PARTICIPANT (TOUR_ANNEE, PART_NUM))   ;

ALTER TABLE TOUR ADD (
     CONSTRAINT FK_TOUR_UTILISATEUR
          FOREIGN KEY (UTIL_NUM_MANAGER)
               REFERENCES UTILISATEUR (UTIL_NUM))   ;

ALTER TABLE TOUR ADD (
     CONSTRAINT FK_TOUR_UTILISATEUR2
          FOREIGN KEY (UTIL_NUM_ADMINISTRER)
               REFERENCES UTILISATEUR (UTIL_NUM))   ;

ALTER TABLE DIRIGER ADD (
     CONSTRAINT FK_DIRIGER_EQUIPE
          FOREIGN KEY (TOUR_ANNEE, EQUIPE_NUM)
               REFERENCES EQUIPE (TOUR_ANNEE, EQUIPE_NUM))   ;

ALTER TABLE DIRIGER ADD (
     CONSTRAINT FK_DIRIGER_DIRECTEUR_SPORTIF
          FOREIGN KEY (DIRS_NUM)
               REFERENCES DIRECTEUR_SPORTIF (DIRS_NUM))   ;

ALTER TABLE CONSULTER ADD (
     CONSTRAINT FK_CONSULTER_TOUR
          FOREIGN KEY (TOUR_ANNEE)
               REFERENCES TOUR (TOUR_ANNEE))   ;

ALTER TABLE CONSULTER ADD (
     CONSTRAINT FK_CONSULTER_UTILISATEUR
          FOREIGN KEY (UTIL_NUM)
               REFERENCES UTILISATEUR (UTIL_NUM))   ;

ALTER TABLE TERMINER_ETAPE_EQUIPE ADD (
     CONSTRAINT FK_TERMINER_ETAPE_EQUIPE_EQUIP
          FOREIGN KEY (TOUR_ANNEE, EQUIPE_NUM)
               REFERENCES EQUIPE (TOUR_ANNEE, EQUIPE_NUM))   ;

ALTER TABLE TERMINER_ETAPE_EQUIPE ADD (
     CONSTRAINT FK_TERMINER_ETAPE_EQUIPE_ETAPE
          FOREIGN KEY (TOUR_ANNEE, ETAPE_NUM)
               REFERENCES ETAPE (TOUR_ANNEE, ETAPE_NUM))   ;

ALTER TABLE VOTER_COMBATIF ADD (
     CONSTRAINT FK_VOTER_COMBATIF_SPECIALISTE
          FOREIGN KEY (SPE_NUM)
               REFERENCES SPECIALISTE (SPE_NUM))   ;

ALTER TABLE VOTER_COMBATIF ADD (
     CONSTRAINT FK_VOTER_COMBATIF_ETAPE
          FOREIGN KEY (TOUR_ANNEE, ETAPE_NUM)
               REFERENCES ETAPE (TOUR_ANNEE, ETAPE_NUM))   ;

ALTER TABLE VOTER_COMBATIF ADD (
     CONSTRAINT FK_VOTER_COMBATIF_PARTICIPANT
          FOREIGN KEY (TOUR_ANNEE, PART_NUM)
               REFERENCES PARTICIPANT (TOUR_ANNEE, PART_NUM))   ;

ALTER TABLE TERMINER_ETAPE ADD (
     CONSTRAINT FK_TERMINER_ETAPE_PARTICIPANT
          FOREIGN KEY (TOUR_ANNEE, PART_NUM)
               REFERENCES PARTICIPANT (TOUR_ANNEE, PART_NUM))   ;

ALTER TABLE TERMINER_ETAPE ADD (
     CONSTRAINT FK_TERMINER_ETAPE_ETAPE
          FOREIGN KEY (TOUR_ANNEE, ETAPE_NUM)
               REFERENCES ETAPE (TOUR_ANNEE, ETAPE_NUM))   ;

ALTER TABLE PORTER ADD (
     CONSTRAINT FK_PORTER_PARTICIPANT
          FOREIGN KEY (TOUR_ANNEE, PART_NUM)
               REFERENCES PARTICIPANT (TOUR_ANNEE, PART_NUM))   ;

ALTER TABLE PORTER ADD (
     CONSTRAINT FK_PORTER_ETAPE
          FOREIGN KEY (TOUR_ANNEE, ETAPE_NUM)
               REFERENCES ETAPE (TOUR_ANNEE, ETAPE_NUM))   ;

ALTER TABLE PASSER ADD (
     CONSTRAINT FK_PASSER_POINT_PASSAGE
          FOREIGN KEY (TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM)
               REFERENCES POINT_PASSAGE (TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM))   ;

ALTER TABLE PASSER ADD (
     CONSTRAINT FK_PASSER_PARTICIPANT
          FOREIGN KEY (TOUR_ANNEE, PART_NUM)
               REFERENCES PARTICIPANT (TOUR_ANNEE, PART_NUM))   ;

ALTER TABLE VOTER_SUPER_COMBATIF ADD (
     CONSTRAINT FK_VOTER_SUPER_COMBATIF_PARTIC
          FOREIGN KEY (TOUR_ANNEE, PART_NUM)
               REFERENCES PARTICIPANT (TOUR_ANNEE, PART_NUM))   ;

ALTER TABLE VOTER_SUPER_COMBATIF ADD (
     CONSTRAINT FK_VOTER_SUPER_COMBATIF_TOUR
          FOREIGN KEY (TOUR_ANNEE)
               REFERENCES TOUR (TOUR_ANNEE))   ;

ALTER TABLE VOTER_SUPER_COMBATIF ADD (
     CONSTRAINT FK_VOTER_SUPER_COMBATIF_SPECIA
          FOREIGN KEY (SPE_NUM)
               REFERENCES SPECIALISTE (SPE_NUM))   ;
