ALTER TABLE PORTER
ADD CONSTRAINT chk_maillot CHECK (MAILLOT_COULEUR='jaune' OR MAILLOT_COULEUR='vert' OR MAILLOT_COULEUR='pois' OR MAILLOT_COULEUR='blanc' OR MAILLOT_COULEUR='rouge');

ALTER TABLE CATEGORIE
ADD CONSTRAINT chk_maillot_cat CHECK (MAILLOT_COULEUR='jaune' OR MAILLOT_COULEUR='vert' OR MAILLOT_COULEUR='pois' OR MAILLOT_COULEUR='blanc');

ALTER TABLE ETAPE
ADD CONSTRAINT chk_tetape CHECK (TETAPE_LIB='ligne' OR TETAPE_LIB='clmi' OR TETAPE_LIB='clme' OR TETAPE_LIB='prologue');