CREATE SEQUENCE seq_cycliste START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_pays START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_dirs START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_ville START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_categorie START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_utilisateur START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_controle START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_specialiste START WITH 1 INCREMENT BY 1;