DROP TABLE DIRECTEUR_SPORTIF CASCADE CONSTRAINTS;

DROP TABLE CYCLISTE CASCADE CONSTRAINTS;

DROP TABLE CATEGORIE CASCADE CONSTRAINTS;

DROP TABLE UTILISATEUR CASCADE CONSTRAINTS;

DROP TABLE PARTICIPANT CASCADE CONSTRAINTS;

DROP TABLE PAYS CASCADE CONSTRAINTS;

DROP TABLE BAREME CASCADE CONSTRAINTS;

DROP TABLE EQUIPE CASCADE CONSTRAINTS;

DROP TABLE VILLE CASCADE CONSTRAINTS;

DROP TABLE POINT_PASSAGE CASCADE CONSTRAINTS;

DROP TABLE SPECIALISTE CASCADE CONSTRAINTS;

DROP TABLE CONTROLE CASCADE CONSTRAINTS;

DROP TABLE ETAPE CASCADE CONSTRAINTS;

DROP TABLE TOUR CASCADE CONSTRAINTS;

DROP TABLE DIRIGER CASCADE CONSTRAINTS;

DROP TABLE CONSULTER CASCADE CONSTRAINTS;

DROP TABLE TERMINER_ETAPE_EQUIPE CASCADE CONSTRAINTS;

DROP TABLE VOTER_COMBATIF CASCADE CONSTRAINTS;

DROP TABLE TERMINER_ETAPE CASCADE CONSTRAINTS;

DROP TABLE PORTER CASCADE CONSTRAINTS;

DROP TABLE PASSER CASCADE CONSTRAINTS;

DROP TABLE VOTER_SUPER_COMBATIF CASCADE CONSTRAINTS;