
DELETE FROM PASSER WHERE TOUR_ANNEE = 2014;
DELETE FROM TERMINER_ETAPE WHERE TOUR_ANNEE = 2014;
DELETE FROM TERMINER_ETAPE_EQUIPE WHERE TOUR_ANNEE = 2014;

UPDATE terminer_etape_equipe SET gene_equi_tps = 0 WHERE gene_equi_tps IS NULL; 

-- Visualisation 

SELECT * FROM POINT_PASSAGE WHERE TOUR_ANNEE = 2014 AND ETAPE_NUM = 1;

SELECT * FROM TERMINER_ETAPE WHERE TOUR_ANNEE = 2014 ORDER BY ETAPE_CLASS;
SELECT * FROM PARTICIPANT WHERE TOUR_ANNEE = 2014 AND PART_NUM IN (1, 2, 3, 4, 11, 12, 13, 14, 21, 22);

SELECT * FROM TERMINER_ETAPE_EQUIPE WHERE TOUR_ANNEE = 2014 ORDER BY ETAPE_EQUI_CLASS;
SELECT * FROM EQUIPE WHERE TOUR_ANNEE = 2014;

--Insertion dans la table passer
BEGIN
--1er Point de passage
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 1, 1, 0);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 1, 2, 0);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 1, 3, 0);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 1, 4, 0);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 1, 11, 0);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 1, 12, 0);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 1, 13, 0);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 1, 14, 0);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 1, 21, 0);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 1, 22, 0);

--2ème point de passage
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 2, 1, 1000);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 2, 2, 1100);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 2, 3, 1100);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 2, 4, 1100);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 2, 11, 2000);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 2, 12, 2100);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 2, 13, 2200);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 2, 14, 2200);

INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 2, 21, 2200);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 2, 22, 2300);

--3ème point de passage
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 3, 11, 2800);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 3, 1, 3000);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 3, 2, 3100);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 3, 12, 3200);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 3, 3, 3300);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 3, 21, 3400);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 3, 14, 3400);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 3, 4, 3500);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 3, 13, 3500);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 3, 22, 3600);

--4ème point de passage
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 4, 1, 4000);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 4, 11, 4000);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 4, 2, 4500);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 4, 3, 4600);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 4, 12, 4800);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 4, 14, 4800);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 4, 4, 4900);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 4, 13, 5000);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 4, 21, 5100);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 4, 22, 5100);

--5ème point de passage
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 5, 1, 6000);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 5, 11, 6100);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 5, 21, 6200);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 5, 2, 6300);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 5, 3, 6400);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 5, 12, 6600);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 5, 14, 6600);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 5, 4, 6600);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 5, 13, 6600);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 5, 21, 6600);
INSERT INTO PASSER(TOUR_ANNEE, ETAPE_NUM, PT_PASS_NUM, PART_NUM, PASS_TPS)
VALUES(2014, 1, 5, 22, 6600);
